# Generated by Django 2.1 on 2018-08-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thum',
            new_name='thumb',
        ),
    ]
