# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='key_words',
            field=models.TextField(default=None),
        ),
    ]
