# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='key_words',
            field=models.TextField(),
        ),
    ]
