# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0011_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyOnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('up_vote', models.PositiveSmallIntegerField()),
                ('down_vote', models.PositiveSmallIntegerField()),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
