# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20181211_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(default=b'public', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replyoncomment',
            name='approved',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='replyoncomment',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
