# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_replyoncomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
