# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
