# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20181218_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
