# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20181218_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
